trigger:
  branches:
    include:
    - main
    - feature/*
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: github.com_idg10

jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'

  steps:
  - template: templates/install-net-runtimes-and-sdks.yaml
    parameters:
      runtimes: [2.1.x, 3.1.x]
      sdks: [5.x]
  # - task: UseDotNet@2
  #   inputs:
  #     packageType: 'runtime'
  #     version: '3.1.x'

  # - task: UseDotNet@2
  #   displayName: 'Install .NET Core SDK 5.x'
  #   inputs:
  #     packageType: sdk
  #     version: 5.x
  #     installationPath: $(Agent.ToolsDirectory)/dotnet  

  # - powershell: |
  #     nuget sources
  #     dotnet --info
  #   displayName: 'NuGet sources 2'

  # - powershell: |
  #     Get-ChildItem $HOME -r
  #   displayName: 'Dump home folder'

  - task: DotNetCoreCLI@2
    displayName: 'Install GitVersion (Global Tools Linux Build Agent Workaround)'
    inputs:
      command: custom
      custom: 'tool'
      arguments: 'install -g GitVersion.Tool --version 5.6.6'

  - script: 'dotnet-gitversion /output buildserver /nofetch'
    name: 'RunGitVersion'
    displayName: 'Run GitVersion'
# - template: templates/build.and.release.yml@recommended_practices
#   parameters:
#     vmImage: 'windows-latest'
#     service_connection_nuget_org: $(Idg10_Service_Connection_NuGet_Org)
#     service_connection_github: $(Idg10_Service_Connection_GitHub)
#     solution_to_build: $(Idg_Solution_To_Build)
#     netSdkVersion: '3.x'