trigger:
  branches:
    include:
    - main
    - feature/*
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: github.com_idg10

jobs:
- template: job-template.yml
  parameters:
    #vmImage: 'windows-latest'
    vmImage: 'ubuntu-latest'
    solution_to_build: 'Solutions/CheckGitversion.sln'
    runtimes: [2.1.x, 3.1.x]
    sdk: 5.x
    #sdks: [3.x, 5.x]
