trigger:
  branches:
    include:
    - main
    - feature/*
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: github.com_idg10

jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'

  steps:
  - powershell: |
      Get-ChildItem $HOME -r -r
    displayName: 'Dump home folder'

# - template: templates/build.and.release.yml@recommended_practices
#   parameters:
#     vmImage: 'windows-latest'
#     service_connection_nuget_org: $(Idg10_Service_Connection_NuGet_Org)
#     service_connection_github: $(Idg10_Service_Connection_GitHub)
#     solution_to_build: $(Idg_Solution_To_Build)
#     netSdkVersion: '3.x'