trigger:
  branches:
    include:
    - main
    - feature/*
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: github.com_idg10

jobs:
# - job: Build
#   pool:
#     vmImage: 'windows-latest'

#   variables:
#     SolutionToBuild: Solutions/CheckGitversion.sln
#     BuildConfiguration: Release

#   steps:
#   - template: install-net-runtimes-and-sdks.yml
#     parameters:
#       runtimes: [2.1.x, 3.1.x]
#       sdk: 5.x
#
- template: job-template.yml
  parameters:
    vmImage: 'ubuntu-latest'
    runtimes: [2.1.x, 3.1.x]
    sdks: [3.1, 5.x]
    #sdk: 5.x
