# To be able to use template expressions in variable sections, it seems we can't use
# a step template, because we can't actually put a variables section in at the top.
# So we need to make a whole job template.
# Actually, is that true, or is it just that I hit the "Mapping values not allowed"
# error and initially misunderstood it?

parameters:
- name: runtimes
  type: object
  default:
  - 3.1.x
- name: sdks
  type: object
  default: []
- name: sdk
  type: string
  default: "5.x"
- name: vmImage
  type: string
  default: ""


jobs:
- job: Build
  pool:
    vmImage: ${{ parameters.vmImage }}

  # variables:
  #   ${{ if and(parameters.sdks, ge(length(parameters.sdks), 0)) }}:
  #     sdkList: $[ parameters.sdks ]
  #   ${{ if and(not(parameters.sdks), parameters.sdk) }}:
  #     sdkList: ["${{ parameters.sdk }}"]

  steps:
  - powershell: |
      write-host $env:c1
      write-host $env:c2
      write-host $env:r1
      write-host $env:r2
      write-host $env:r3
      write-host $env:r4
      write-host ${{ parameters.sdk }}
      write-host $env:t1
      write-host $env:t2
      write-host $env:t3
      write-host $env:t4
    env:
      c1: ${{ and(parameters.sdks, ge(length(parameters.sdks), 0)) }}
      c2: ${{ not(and(parameters.sdks, ge(length(parameters.sdks), 0))) }}
      r1: ${{ join(',', parameters.runtimes) }}
      r2: "${{ join(',', parameters.runtimes) }}"
      r3: '[${{ join(',', parameters.runtimes) }}]'
      r4: '["${{ join(',', parameters.runtimes) }}"]'
      t1: ${{ parameters.sdk }}
      t2: "${{ parameters.sdk }}"
      t3: '[${{ parameters.sdk }}]'
      t4: '["${{ parameters.sdk }}"]'
    displayName: 'Dump parameters'

  - template: install-net-runtimes-and-sdks.yml
    parameters:
      runtimes: ${{ parameters.runtimes }}
#      sdks: ${{ variables.sdkList }}
      ${{ if and(parameters.sdks, ge(length(parameters.sdks), 0)) }}:
        sdks: ${{ parameters.sdks }}
      ${{ if not(and(parameters.sdks, ge(length(parameters.sdks), 0))) }}:
        sdks: ["${{ parameters.sdk }}"]


  - task: DotNetCoreCLI@2
    displayName: 'Install GitVersion (Global Tools Linux Build Agent Workaround)'
    inputs:
      command: custom
      custom: 'tool'
      arguments: 'install -g GitVersion.Tool --version 5.6.6'

  - script: 'dotnet-gitversion /output buildserver /nofetch'
    name: 'RunGitVersion'
    displayName: 'Run GitVersion'

  - task: DotNetCoreCLI@2
    displayName: 'Restore & Build'
    inputs:
      command: 'build'
      projects: $(SolutionToBuild)
      arguments: '--configuration $(BuildConfiguration) /p:Version=$(GitVersion.SemVer)'
      #versioningScheme: byBuildNumber
      #buildProperties: 'EndjinRepositoryUrl="$(Build.Repository.Uri)"'

  - task: DotNetCoreCLI@2
    displayName: 'Run Executable Specifications'
    inputs:
      command: 'test'
      projects: $(SolutionToBuild)
      arguments: '-c $(BuildConfiguration) --no-build --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'

# - template: templates/build.and.release.yml@recommended_practices
#   parameters:
#     vmImage: 'windows-latest'
#     service_connection_nuget_org: $(Idg10_Service_Connection_NuGet_Org)
#     service_connection_github: $(Idg10_Service_Connection_GitHub)
#     solution_to_build: $(Idg_Solution_To_Build)
#     netSdkVersion: '3.x'